### ISSUE TITLE
Take advantage of enumerable methods

### ISSUE THREAD

**Issue by naush** [ranizilpelwar/tic_tac_toe_rz#3]
Ruby has a big collection of enumerable methods to help with searching and filtering through collection. Study them will help your code look more concise and expressive.

Here is an example:

```rb
board.each do |tile_on_board| 
  if digit?(tile_on_board)
    index = board.index(tile_on_board)
    available_spaces.push(index)
  end
end
```

May be rewritten as

```rb
board.each_with_index do |tile_on_board, index| 
  if digit?(tile_on_board)
    available_spaces.push(index)
  end
end
```

```rb
board.select do |tile_on_board| 
  digit?(tile_on_board)
end.each do |tile_on_board|
  index = board.index(tile_on_board)
  available_spaces.push(index)
end
```

Code not tested, but you get the point. Check out [Enumerable](https://ruby-doc.org/core-2.2.0/Enumerable.html).

**Comment by ranizilpelwar** [comment]
[IssueFixesReTests 8c09e18]
